Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: nodejs16.x
    Timeout: 120
    Handler: index.handler

Resources:
    dynamoDbAPI:
      Type: AWS::Serverless::Api
      Properties:
        Name: 'dynamoDbAPI'
        StageName: 'v1'
        OpenApiVersion: '3.0.2'
        DefinitionBody:
          Fn::Transform:
            Name: AWS::Include
            Parameters:
              Location: ./swagger.yaml
    CreateDynamoDbFunction:
      Type: AWS::Serverless::Function
      Properties:
        CodeUri: functions/create-dynamodb/
        Description: To Create an AWS DynamoDb table
    GetItemFunction:
      Type: AWS::Serverless::Function
      Properties:
        CodeUri: functions/get-item/
        Description: To fetch a item from DynamoDb table
        Events:
         Get:
          Type: Api
          Properties:
           RestApiId:
              Ref: dynamoDbAPI
           Path: /
           Method: GET  
    PutItemFunction:
      Type: AWS::Serverless::Function
      Properties:
        CodeUri: functions/put-item/
        Description: To add a item in DynamoDb table
        Events:
         Post:
          Type: Api
          Properties:
           RestApiId:
             Ref: dynamoDbAPI
           Path: /
           Method: POST
    UpdateItemFunction:
      Type: AWS::Serverless::Function
      Properties:
         CodeUri: functions/update-item/
         Description: To update a item in DynamoDb table   
         Events:
          Put:
           Type: Api
           Properties:
            RestApiId:
              Ref: dynamoDbAPI
            Path: /
            Method: PUT       
    